on:
  push:
    branches:
      - 'main'
jobs:
  glitch-sync:
    runs-on: ubuntu-latest
    steps:
    - name: glitch-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/dansakamoto/impossible-day-3a.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: ${{ secrets.glitch_git_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
